version: "3.13"
services:
  portal_api:
    container_name: portal_api
    build:
      context: ..
      dockerfile: ./koereskoleportalen/Portal.API/Dockerfile
    ports:
      - "5051:8080"
    depends_on: 
      - portal_mongodb
    networks:
      - backend_network
  portal_client:
    container_name: portal_client
    build:
      context: ..
      dockerfile: ./koereskoleportalen/Portal.Client/Dockerfile
    ports:
      - "5173:5173"
  rabbitmq3:
    container_name: "rabbitmq"
    hostname: koereskoleportalen-mq
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - backend_network
  postgres_backoffice:
    container_name: "postgres_backoffice_compose"
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_BACKOFFICE_DBNAME}
      - PGPORT=5432
    ports:
      - '5432:5432'
    networks:
      - backend_network
  postgres_identity:
    container_name: "postgres_identity_compose"
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_IDENTITY_DBNAME}
      - PGPORT=5442
    ports:
      - '5442:5442'
    networks:
      - backend_network
  portal_mongodb:
    container_name: "portal_mongodb"
    image: "mongo:latest"
    ports:
      - '27017:27017'
    networks:
      - backend_network
  sync_service:
    container_name: sync_service
    build:
      context: ..
      dockerfile: ./koereskoleportalen/Synchronization.Service/dockerfile
    ports:
      - '5673:5673'
    depends_on:
      - portal_mongodb
      - rabbitmq3
    networks:
      - backend_network
    

networks:
  backend_network:
    
    
    