#RABBITMQ
RABBITMQ_USER = 'Admin'
RABBITMQ_PASSWORD = 'Admin2024'
RABBITMQ_HOST = 'localhost'
RABBITMQ_PORT = 5672
RABBITMQ_VHOST = '/'

#MONGODB
MONGO_HOST = 'localhost'
MONGO_PORT = 27017
MONGO_DB_NAME = 'koereskoleportalen-portal'
MONGO_DB_COLLECTION = 'companies'