# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app
# Use this for docker compose instead of the above
# COPY "./koereskoleportalen/Synchronization.Service/" /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 5672 available to the world outside this container if needed
EXPOSE 5672

# Set environment variables
ENV RABBITMQ_USER=Admin
ENV RABBITMQ_PASSWORD=Admin2024
ENV RABBITMQ_HOST=rabbitmq
ENV RABBITMQ_PORT=5672
ENV RABBITMQ_VHOST=/
ENV MONGO_HOST=portal_mongodb
ENV MONGO_PORT=27017
ENV MONGO_DB_NAME=koereskoleportalen-portal
ENV MONGO_DS_COLLECTION=drivingschools
ENV MONGO_ORG_COLLECTION=organisations

# Command to run the application
CMD ["python", "sync.py"]
