### YamlMime:ManagedReference
items:
- uid: CvrSync.Service.Models.CvrAuthenticationSettings
  commentId: T:CvrSync.Service.Models.CvrAuthenticationSettings
  id: CvrAuthenticationSettings
  parent: CvrSync.Service.Models
  children:
  - CvrSync.Service.Models.CvrAuthenticationSettings.Password
  - CvrSync.Service.Models.CvrAuthenticationSettings.Username
  langs:
  - csharp
  - vb
  name: CvrAuthenticationSettings
  nameWithType: CvrAuthenticationSettings
  fullName: CvrSync.Service.Models.CvrAuthenticationSettings
  type: Class
  source:
    remote:
      path: CvrSync.Service/Models/EnvironmentSettings/CvrAuthenticationSettings.cs
      branch: main
      repo: https://github.com/melander2910/koereskoleportalen.git
    id: CvrAuthenticationSettings
    path: ../CvrSync.Service/Models/EnvironmentSettings/CvrAuthenticationSettings.cs
    startLine: 2
  assemblies:
  - CvrSync.Service
  namespace: CvrSync.Service.Models
  syntax:
    content: public class CvrAuthenticationSettings
    content.vb: Public Class CvrAuthenticationSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: CvrSync.Service.Models.CvrAuthenticationSettings.Username
  commentId: P:CvrSync.Service.Models.CvrAuthenticationSettings.Username
  id: Username
  parent: CvrSync.Service.Models.CvrAuthenticationSettings
  langs:
  - csharp
  - vb
  name: Username
  nameWithType: CvrAuthenticationSettings.Username
  fullName: CvrSync.Service.Models.CvrAuthenticationSettings.Username
  type: Property
  source:
    remote:
      path: CvrSync.Service/Models/EnvironmentSettings/CvrAuthenticationSettings.cs
      branch: main
      repo: https://github.com/melander2910/koereskoleportalen.git
    id: Username
    path: ../CvrSync.Service/Models/EnvironmentSettings/CvrAuthenticationSettings.cs
    startLine: 4
  assemblies:
  - CvrSync.Service
  namespace: CvrSync.Service.Models
  syntax:
    content: public string Username { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Username As String
  overload: CvrSync.Service.Models.CvrAuthenticationSettings.Username*
- uid: CvrSync.Service.Models.CvrAuthenticationSettings.Password
  commentId: P:CvrSync.Service.Models.CvrAuthenticationSettings.Password
  id: Password
  parent: CvrSync.Service.Models.CvrAuthenticationSettings
  langs:
  - csharp
  - vb
  name: Password
  nameWithType: CvrAuthenticationSettings.Password
  fullName: CvrSync.Service.Models.CvrAuthenticationSettings.Password
  type: Property
  source:
    remote:
      path: CvrSync.Service/Models/EnvironmentSettings/CvrAuthenticationSettings.cs
      branch: main
      repo: https://github.com/melander2910/koereskoleportalen.git
    id: Password
    path: ../CvrSync.Service/Models/EnvironmentSettings/CvrAuthenticationSettings.cs
    startLine: 5
  assemblies:
  - CvrSync.Service
  namespace: CvrSync.Service.Models
  syntax:
    content: public string Password { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Password As String
  overload: CvrSync.Service.Models.CvrAuthenticationSettings.Password*
references:
- uid: CvrSync.Service.Models
  commentId: N:CvrSync.Service.Models
  href: CvrSync.html
  name: CvrSync.Service.Models
  nameWithType: CvrSync.Service.Models
  fullName: CvrSync.Service.Models
  spec.csharp:
  - uid: CvrSync
    name: CvrSync
    href: CvrSync.html
  - name: .
  - uid: CvrSync.Service
    name: Service
    href: CvrSync.Service.html
  - name: .
  - uid: CvrSync.Service.Models
    name: Models
    href: CvrSync.Service.Models.html
  spec.vb:
  - uid: CvrSync
    name: CvrSync
    href: CvrSync.html
  - name: .
  - uid: CvrSync.Service
    name: Service
    href: CvrSync.Service.html
  - name: .
  - uid: CvrSync.Service.Models
    name: Models
    href: CvrSync.Service.Models.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: CvrSync.Service.Models.CvrAuthenticationSettings.Username*
  commentId: Overload:CvrSync.Service.Models.CvrAuthenticationSettings.Username
  href: CvrSync.Service.Models.CvrAuthenticationSettings.html#CvrSync_Service_Models_CvrAuthenticationSettings_Username
  name: Username
  nameWithType: CvrAuthenticationSettings.Username
  fullName: CvrSync.Service.Models.CvrAuthenticationSettings.Username
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: CvrSync.Service.Models.CvrAuthenticationSettings.Password*
  commentId: Overload:CvrSync.Service.Models.CvrAuthenticationSettings.Password
  href: CvrSync.Service.Models.CvrAuthenticationSettings.html#CvrSync_Service_Models_CvrAuthenticationSettings_Password
  name: Password
  nameWithType: CvrAuthenticationSettings.Password
  fullName: CvrSync.Service.Models.CvrAuthenticationSettings.Password
