apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./kubernetes/
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: portal-api
  name: portal_api
spec:
  ports:
    - name: "5051"
      port: 5051
      targetPort: 8080
  selector:
    io.kompose.service: portal-api
