apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./kubernetes/
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: portal-mongodb
  name: portal-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: portal-mongodb
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./kubernetes/
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/koereskoleportalen-backend-network: "true"
        io.kompose.service: portal-mongodb
    spec:
      containers:
        - image: mongo:latest
          name: portal-mongodb
          ports:
            - containerPort: 27017
              hostPort: 27017
              protocol: TCP
      restartPolicy: Always
