apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./kubernetes/
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: postgres-identity
  name: postgres-identity
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-identity
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./kubernetes/
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/koereskoleportalen-backend-network: "true"
        io.kompose.service: postgres-identity
    spec:
      containers:
        - env:
            - name: PGPORT
              value: "5442"
            - name: POSTGRES_DB
            - name: POSTGRES_PASSWORD
            - name: POSTGRES_USER
          image: postgres:latest
          name: postgres-identity-compose
          ports:
            - containerPort: 5442
              hostPort: 5442
              protocol: TCP
      restartPolicy: Always
