apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./kubernetes/
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: rabbitmq3
  name: rabbitmq3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rabbitmq3
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./kubernetes/
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/koereskoleportalen-backend-network: "true"
        io.kompose.service: rabbitmq3
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_PASS
            - name: RABBITMQ_DEFAULT_USER
          image: rabbitmq:management
          name: rabbitmq
          ports:
            - containerPort: 5672
              hostPort: 5672
              protocol: TCP
            - containerPort: 15672
              hostPort: 15672
              protocol: TCP
      hostname: koereskoleportalen-mq
      restartPolicy: Always
