apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./kubernetes/
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: sync-service
  name: sync_service
spec:
  ports:
    - name: "5673"
      port: 5673
      targetPort: 5673
  selector:
    io.kompose.service: sync-service
