### YamlMime:ManagedReference
items:
- uid: Portal.API.Models.PortalDatabaseSettings
  commentId: T:Portal.API.Models.PortalDatabaseSettings
  id: PortalDatabaseSettings
  parent: Portal.API.Models
  children:
  - Portal.API.Models.PortalDatabaseSettings.ConnectionString
  - Portal.API.Models.PortalDatabaseSettings.DatabaseName
  - Portal.API.Models.PortalDatabaseSettings.DrivingSchoolsCollectionName
  - Portal.API.Models.PortalDatabaseSettings.OrganisationsCollectionName
  langs:
  - csharp
  - vb
  name: PortalDatabaseSettings
  nameWithType: PortalDatabaseSettings
  fullName: Portal.API.Models.PortalDatabaseSettings
  type: Class
  source:
    remote:
      path: Portal.API/Models/PortalDatabaseSettings.cs
      branch: docfx
      repo: https://github.com/melander2910/koereskoleportalen.git
    id: PortalDatabaseSettings
    path: Portal.API/Models/PortalDatabaseSettings.cs
    startLine: 2
  assemblies:
  - Portal.API
  namespace: Portal.API.Models
  syntax:
    content: public class PortalDatabaseSettings
    content.vb: Public Class PortalDatabaseSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Portal.API.Models.PortalDatabaseSettings.ConnectionString
  commentId: P:Portal.API.Models.PortalDatabaseSettings.ConnectionString
  id: ConnectionString
  parent: Portal.API.Models.PortalDatabaseSettings
  langs:
  - csharp
  - vb
  name: ConnectionString
  nameWithType: PortalDatabaseSettings.ConnectionString
  fullName: Portal.API.Models.PortalDatabaseSettings.ConnectionString
  type: Property
  source:
    remote:
      path: Portal.API/Models/PortalDatabaseSettings.cs
      branch: docfx
      repo: https://github.com/melander2910/koereskoleportalen.git
    id: ConnectionString
    path: Portal.API/Models/PortalDatabaseSettings.cs
    startLine: 4
  assemblies:
  - Portal.API
  namespace: Portal.API.Models
  syntax:
    content: public string ConnectionString { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ConnectionString As String
  overload: Portal.API.Models.PortalDatabaseSettings.ConnectionString*
- uid: Portal.API.Models.PortalDatabaseSettings.DatabaseName
  commentId: P:Portal.API.Models.PortalDatabaseSettings.DatabaseName
  id: DatabaseName
  parent: Portal.API.Models.PortalDatabaseSettings
  langs:
  - csharp
  - vb
  name: DatabaseName
  nameWithType: PortalDatabaseSettings.DatabaseName
  fullName: Portal.API.Models.PortalDatabaseSettings.DatabaseName
  type: Property
  source:
    remote:
      path: Portal.API/Models/PortalDatabaseSettings.cs
      branch: docfx
      repo: https://github.com/melander2910/koereskoleportalen.git
    id: DatabaseName
    path: Portal.API/Models/PortalDatabaseSettings.cs
    startLine: 6
  assemblies:
  - Portal.API
  namespace: Portal.API.Models
  syntax:
    content: public string DatabaseName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property DatabaseName As String
  overload: Portal.API.Models.PortalDatabaseSettings.DatabaseName*
- uid: Portal.API.Models.PortalDatabaseSettings.OrganisationsCollectionName
  commentId: P:Portal.API.Models.PortalDatabaseSettings.OrganisationsCollectionName
  id: OrganisationsCollectionName
  parent: Portal.API.Models.PortalDatabaseSettings
  langs:
  - csharp
  - vb
  name: OrganisationsCollectionName
  nameWithType: PortalDatabaseSettings.OrganisationsCollectionName
  fullName: Portal.API.Models.PortalDatabaseSettings.OrganisationsCollectionName
  type: Property
  source:
    remote:
      path: Portal.API/Models/PortalDatabaseSettings.cs
      branch: docfx
      repo: https://github.com/melander2910/koereskoleportalen.git
    id: OrganisationsCollectionName
    path: Portal.API/Models/PortalDatabaseSettings.cs
    startLine: 8
  assemblies:
  - Portal.API
  namespace: Portal.API.Models
  syntax:
    content: public string OrganisationsCollectionName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property OrganisationsCollectionName As String
  overload: Portal.API.Models.PortalDatabaseSettings.OrganisationsCollectionName*
- uid: Portal.API.Models.PortalDatabaseSettings.DrivingSchoolsCollectionName
  commentId: P:Portal.API.Models.PortalDatabaseSettings.DrivingSchoolsCollectionName
  id: DrivingSchoolsCollectionName
  parent: Portal.API.Models.PortalDatabaseSettings
  langs:
  - csharp
  - vb
  name: DrivingSchoolsCollectionName
  nameWithType: PortalDatabaseSettings.DrivingSchoolsCollectionName
  fullName: Portal.API.Models.PortalDatabaseSettings.DrivingSchoolsCollectionName
  type: Property
  source:
    remote:
      path: Portal.API/Models/PortalDatabaseSettings.cs
      branch: docfx
      repo: https://github.com/melander2910/koereskoleportalen.git
    id: DrivingSchoolsCollectionName
    path: Portal.API/Models/PortalDatabaseSettings.cs
    startLine: 9
  assemblies:
  - Portal.API
  namespace: Portal.API.Models
  syntax:
    content: public string DrivingSchoolsCollectionName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property DrivingSchoolsCollectionName As String
  overload: Portal.API.Models.PortalDatabaseSettings.DrivingSchoolsCollectionName*
references:
- uid: Portal.API.Models
  commentId: N:Portal.API.Models
  href: Portal.html
  name: Portal.API.Models
  nameWithType: Portal.API.Models
  fullName: Portal.API.Models
  spec.csharp:
  - uid: Portal
    name: Portal
    href: Portal.html
  - name: .
  - uid: Portal.API
    name: API
    href: Portal.API.html
  - name: .
  - uid: Portal.API.Models
    name: Models
    href: Portal.API.Models.html
  spec.vb:
  - uid: Portal
    name: Portal
    href: Portal.html
  - name: .
  - uid: Portal.API
    name: API
    href: Portal.API.html
  - name: .
  - uid: Portal.API.Models
    name: Models
    href: Portal.API.Models.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Portal.API.Models.PortalDatabaseSettings.ConnectionString*
  commentId: Overload:Portal.API.Models.PortalDatabaseSettings.ConnectionString
  href: Portal.API.Models.PortalDatabaseSettings.html#Portal_API_Models_PortalDatabaseSettings_ConnectionString
  name: ConnectionString
  nameWithType: PortalDatabaseSettings.ConnectionString
  fullName: Portal.API.Models.PortalDatabaseSettings.ConnectionString
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Portal.API.Models.PortalDatabaseSettings.DatabaseName*
  commentId: Overload:Portal.API.Models.PortalDatabaseSettings.DatabaseName
  href: Portal.API.Models.PortalDatabaseSettings.html#Portal_API_Models_PortalDatabaseSettings_DatabaseName
  name: DatabaseName
  nameWithType: PortalDatabaseSettings.DatabaseName
  fullName: Portal.API.Models.PortalDatabaseSettings.DatabaseName
- uid: Portal.API.Models.PortalDatabaseSettings.OrganisationsCollectionName*
  commentId: Overload:Portal.API.Models.PortalDatabaseSettings.OrganisationsCollectionName
  href: Portal.API.Models.PortalDatabaseSettings.html#Portal_API_Models_PortalDatabaseSettings_OrganisationsCollectionName
  name: OrganisationsCollectionName
  nameWithType: PortalDatabaseSettings.OrganisationsCollectionName
  fullName: Portal.API.Models.PortalDatabaseSettings.OrganisationsCollectionName
- uid: Portal.API.Models.PortalDatabaseSettings.DrivingSchoolsCollectionName*
  commentId: Overload:Portal.API.Models.PortalDatabaseSettings.DrivingSchoolsCollectionName
  href: Portal.API.Models.PortalDatabaseSettings.html#Portal_API_Models_PortalDatabaseSettings_DrivingSchoolsCollectionName
  name: DrivingSchoolsCollectionName
  nameWithType: PortalDatabaseSettings.DrivingSchoolsCollectionName
  fullName: Portal.API.Models.PortalDatabaseSettings.DrivingSchoolsCollectionName
